### ISSUE TITLE
Change JBoss configuration

### ISSUE THREAD

**Issue by palonsoro** [cloudfoundry-community/jboss-buildpack#3]
Would there be any way to set the JBoss configuration?

Thank you in advance.

**Comment by cgfrost** [comment]
Hi,

Thanks to a new feature in the Java buildpack that has been merged in to this buildpack you can now set any of the configuration using an environment variable. See https://github.com/cloudfoundry-community/jboss-buildpack#configuration-and-extension

**Comment by palonsoro** [comment]
I did not mean that kind of configuration but internal JBoss configuration, like J2EE data sources and so on.

**Comment by cgfrost** [comment]
I see. For that the recommended approach is to fork the buildpack and make the changes you require directly. Then specify your fork as the buildpack to be used when pushing applications.

**Comment by palonsoro** [comment]
Ok. I understand it. I was looking for an alternative to that, but there is not. 

Is there any plan to support such this kind of configuration setting in the future? There are some configuration aspects, like J2EE data sources, that may be too application-specific to require a buildpack fork. 

Personally, I think that it would be a shame to miss some of JBoss features and possibilities due to not being able to perform at least some basic JBoss runtime configuration. For example, it is not possible to deploy many typical full Java EE applications via the JBoss buildpack only because you cannot configure their J2EE data sources.

**Comment by nebhale** [comment]
Those changes will only happen if the community contributes them.  If the project starts getting more adoption, we might revisit that, but at the moment, there simply aren't enough users.

**Comment by palonsoro** [comment]
Ok. I understand this point
