### ISSUE TITLE
Why this buildpack is marked as not-yet-completed in https://github.com/cloudfoundry-community/cf-docs-contrib/wiki/Buildpacks

### ISSUE THREAD

**Issue by dwu-pivotal** [cloudfoundry-community/jboss-buildpack#4]
what's the issues remain?

**Comment by cgfrost** [comment]
There is nothing specific outstanding. Apart from merging in upstream changes from the Java buildpack we don't spend a lot of time on JBoss support. We are always happy to accept community contributions though. I suspect that wiki page hasn't been updated in a while.
