### ISSUE TITLE
jboss v4.0 buildpack

### ISSUE THREAD

**Issue by vik-y** [cloudfoundry-community/jboss-buildpack#5]
Hey, this buildpack supports jboss version 7.1+ only. I need to make a buildpack for jboss v 4.0. I am completely new to buildpacks, where should I start? What kind of tweaks should I make to this buildpack to support jboss v4.0

**Comment by cgfrost** [comment]
Hi,

The best approach is to fork the existing buildpack and make the changes you require. The JBoss version can be configured in the https://github.com/cloudfoundry-community/jboss-buildpack/blob/master/config/jboss.yml file.

**Comment by vik-y** [comment]
Will changing just the jboss version in jboss.yml file work? Actually its a bit difficult to understand the overall framework as I haven't coded in ruby before. Anyways, will try.

**Comment by cgfrost** [comment]
JBoss 4 has many other differences that will probably require additional work. Please remember this is a community buildpack so there is no official support for it. Good luck.

**Comment by vik-y** [comment]
Thanks for your help :+1:
